// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgres://f335b176cc12da1646859978aa71d72bed2348adc40fc5f83f7dd834cdbfb0a6:sk_XD3VRxtSvci1UgNpnzMg5@db.prisma.io:5432/postgres?sslmode=require",
  },
});
